name: forward-velocity-site-2025
services:
- name: web
  source_dir: /
  github:
    repo: kareemadebisi112/forward-velocity-site-2025
    branch: main
    deploy_on_push: true
  build_command: npm install && npm run build
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  health_check:
    http_path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
