name: forward-velocity-site-2025
services:
- name: web
  source_dir: /
  github:
    repo: kareemadebisi112/forward-velocity-site-2025
    branch: main
    deploy_on_push: true
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  build_command: npm ci && npm run build
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
