name: forward-velocity-site-2025
static_sites:
- name: web
  source_dir: /
  github:
    repo: kareemadebisi112/forward-velocity-site-2025
    branch: main
    deploy_on_push: true
  build_command: npm install && npm run build
  output_dir: dist
  index_document: index.html
  error_document: index.html
  catchall_document: index.html
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
